/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

#include <a_samp>

new Text:Background;
new Text:NameRing;
new Text:PassordRing;
new Text:NameField;
new Text:PassordField;
new Text:PasswordText;
new Text:NameText;
new Text:QuitButton;
new Text:ConfirmButton;
new Text:QuitText;
new Text:ConfirmText;
new Text:AnonymousGaming;
new Text:ChromaRPG;
new Text:RegisterButton;
new Text:RegisterText;

public OnFilterScriptInit()
{
	Background = TextDrawCreate(320.000000, 129.000000, "_");
	TextDrawFont(Background, 1);
	TextDrawLetterSize(Background, 0.600000, 23.249914);
	TextDrawTextSize(Background, 299.000000, 124.000000);
	TextDrawSetOutline(Background, 1);
	TextDrawSetShadow(Background, 0);
	TextDrawAlignment(Background, 2);
	TextDrawColor(Background, -1);
	TextDrawBackgroundColor(Background, 255);
	TextDrawBoxColor(Background, -116);
	TextDrawUseBox(Background, 1);
	TextDrawSetProportional(Background, 1);
	TextDrawSetSelectable(Background, 0);

	NameRing = TextDrawCreate(320.000000, 196.000000, "_");
	TextDrawFont(NameRing, 1);
	TextDrawLetterSize(NameRing, 0.583333, 1.199998);
	TextDrawTextSize(NameRing, 297.000000, 101.000000);
	TextDrawSetOutline(NameRing, 1);
	TextDrawSetShadow(NameRing, 0);
	TextDrawAlignment(NameRing, 2);
	TextDrawColor(NameRing, -1);
	TextDrawBackgroundColor(NameRing, 255);
	TextDrawBoxColor(NameRing, 248);
	TextDrawUseBox(NameRing, 1);
	TextDrawSetProportional(NameRing, 1);
	TextDrawSetSelectable(NameRing, 0);

	PassordRing = TextDrawCreate(320.000000, 239.000000, "_");
	TextDrawFont(PassordRing, 1);
	TextDrawLetterSize(PassordRing, 0.583333, 1.199998);
	TextDrawTextSize(PassordRing, 297.000000, 101.000000);
	TextDrawSetOutline(PassordRing, 1);
	TextDrawSetShadow(PassordRing, 0);
	TextDrawAlignment(PassordRing, 2);
	TextDrawColor(PassordRing, -1);
	TextDrawBackgroundColor(PassordRing, 255);
	TextDrawBoxColor(PassordRing, 248);
	TextDrawUseBox(PassordRing, 1);
	TextDrawSetProportional(PassordRing, 1);
	TextDrawSetSelectable(PassordRing, 0);

	NameField = TextDrawCreate(320.000000, 198.000000, "_");
	TextDrawFont(NameField, 1);
	TextDrawLetterSize(NameField, 0.583333, 0.799996);
	TextDrawTextSize(NameField, 297.000000, 98.500000);
	TextDrawSetOutline(NameField, 1);
	TextDrawSetShadow(NameField, 0);
	TextDrawAlignment(NameField, 2);
	TextDrawColor(NameField, -1);
	TextDrawBackgroundColor(NameField, 255);
	TextDrawBoxColor(NameField, -741092405);
	TextDrawUseBox(NameField, 1);
	TextDrawSetProportional(NameField, 1);
	TextDrawSetSelectable(NameField, 0);

	PassordField = TextDrawCreate(320.000000, 240.000000, "_");
	TextDrawFont(PassordField, 1);
	TextDrawLetterSize(PassordField, 0.583333, 0.799996);
	TextDrawTextSize(PassordField, 297.000000, 98.500000);
	TextDrawSetOutline(PassordField, 1);
	TextDrawSetShadow(PassordField, 0);
	TextDrawAlignment(PassordField, 2);
	TextDrawColor(PassordField, -1);
	TextDrawBackgroundColor(PassordField, 255);
	TextDrawBoxColor(PassordField, -741092405);
	TextDrawUseBox(PassordField, 1);
	TextDrawSetProportional(PassordField, 1);
	TextDrawSetSelectable(PassordField, 1);

	PasswordText = TextDrawCreate(267.000000, 214.000000, "Senha");
	TextDrawFont(PasswordText, 1);
	TextDrawLetterSize(PasswordText, 0.379166, 1.600000);
	TextDrawTextSize(PasswordText, 400.000000, 17.000000);
	TextDrawSetOutline(PasswordText, 1);
	TextDrawSetShadow(PasswordText, 0);
	TextDrawAlignment(PasswordText, 1);
	TextDrawColor(PasswordText, -1);
	TextDrawBackgroundColor(PasswordText, 255);
	TextDrawBoxColor(PasswordText, 50);
	TextDrawUseBox(PasswordText, 0);
	TextDrawSetProportional(PasswordText, 1);
	TextDrawSetSelectable(PasswordText, 0);

	NameText = TextDrawCreate(267.000000, 172.000000, "Nome");
	TextDrawFont(NameText, 1);
	TextDrawLetterSize(NameText, 0.379166, 1.600000);
	TextDrawTextSize(NameText, 400.000000, 17.000000);
	TextDrawSetOutline(NameText, 1);
	TextDrawSetShadow(NameText, 0);
	TextDrawAlignment(NameText, 1);
	TextDrawColor(NameText, -1);
	TextDrawBackgroundColor(NameText, 255);
	TextDrawBoxColor(NameText, 50);
	TextDrawUseBox(NameText, 0);
	TextDrawSetProportional(NameText, 1);
	TextDrawSetSelectable(NameText, 0);

	QuitButton = TextDrawCreate(320.000000, 317.000000, "_");
	TextDrawFont(QuitButton, 1);
	TextDrawLetterSize(QuitButton, 0.583333, 1.199998);
	TextDrawTextSize(QuitButton, 297.000000, 101.000000);
	TextDrawSetOutline(QuitButton, 1);
	TextDrawSetShadow(QuitButton, 0);
	TextDrawAlignment(QuitButton, 2);
	TextDrawColor(QuitButton, -1);
	TextDrawBackgroundColor(QuitButton, 255);
	TextDrawBoxColor(QuitButton, -1962934024);
	TextDrawUseBox(QuitButton, 1);
	TextDrawSetProportional(QuitButton, 1);
	TextDrawSetSelectable(QuitButton, 1);

	ConfirmButton = TextDrawCreate(320.000000, 269.000000, "_");
	TextDrawFont(ConfirmButton, 1);
	TextDrawLetterSize(ConfirmButton, 0.583333, 1.199998);
	TextDrawTextSize(ConfirmButton, 297.000000, 101.000000);
	TextDrawSetOutline(ConfirmButton, 1);
	TextDrawSetShadow(ConfirmButton, 0);
	TextDrawAlignment(ConfirmButton, 2);
	TextDrawColor(ConfirmButton, -1);
	TextDrawBackgroundColor(ConfirmButton, 255);
	TextDrawBoxColor(ConfirmButton, 9109752);
	TextDrawUseBox(ConfirmButton, 1);
	TextDrawSetProportional(ConfirmButton, 1);
	TextDrawSetSelectable(ConfirmButton, 1);

	QuitText = TextDrawCreate(308.000000, 314.000000, "Sair");
	TextDrawFont(QuitText, 1);
	TextDrawLetterSize(QuitText, 0.379166, 1.600000);
	TextDrawTextSize(QuitText, 400.000000, 17.000000);
	TextDrawSetOutline(QuitText, 1);
	TextDrawSetShadow(QuitText, 0);
	TextDrawAlignment(QuitText, 1);
	TextDrawColor(QuitText, -1);
	TextDrawBackgroundColor(QuitText, 255);
	TextDrawBoxColor(QuitText, 50);
	TextDrawUseBox(QuitText, 0);
	TextDrawSetProportional(QuitText, 1);
	TextDrawSetSelectable(QuitText, 1);

	ConfirmText = TextDrawCreate(293.000000, 265.000000, "Confirmar");
	TextDrawFont(ConfirmText, 1);
	TextDrawLetterSize(ConfirmText, 0.379166, 1.600000);
	TextDrawTextSize(ConfirmText, 400.000000, 17.000000);
	TextDrawSetOutline(ConfirmText, 1);
	TextDrawSetShadow(ConfirmText, 0);
	TextDrawAlignment(ConfirmText, 1);
	TextDrawColor(ConfirmText, -1);
	TextDrawBackgroundColor(ConfirmText, 255);
	TextDrawBoxColor(ConfirmText, 50);
	TextDrawUseBox(ConfirmText, 0);
	TextDrawSetProportional(ConfirmText, 1);
	TextDrawSetSelectable(ConfirmText, 1);

	AnonymousGaming = TextDrawCreate(320.000000, 127.000000, "Anonymous Gaming");
	TextDrawFont(AnonymousGaming, 3);
	TextDrawLetterSize(AnonymousGaming, 0.379166, 1.600000);
	TextDrawTextSize(AnonymousGaming, 400.000000, 346.500000);
	TextDrawSetOutline(AnonymousGaming, 1);
	TextDrawSetShadow(AnonymousGaming, 0);
	TextDrawAlignment(AnonymousGaming, 2);
	TextDrawColor(AnonymousGaming, 9145343);
	TextDrawBackgroundColor(AnonymousGaming, 255);
	TextDrawBoxColor(AnonymousGaming, 50);
	TextDrawUseBox(AnonymousGaming, 0);
	TextDrawSetProportional(AnonymousGaming, 1);
	TextDrawSetSelectable(AnonymousGaming, 0);

	ChromaRPG = TextDrawCreate(320.000000, 144.000000, "Chroma RPG");
	TextDrawFont(ChromaRPG, 3);
	TextDrawLetterSize(ChromaRPG, 0.379166, 1.600000);
	TextDrawTextSize(ChromaRPG, 400.000000, 346.500000);
	TextDrawSetOutline(ChromaRPG, 1);
	TextDrawSetShadow(ChromaRPG, 0);
	TextDrawAlignment(ChromaRPG, 2);
	TextDrawColor(ChromaRPG, -1962934017);
	TextDrawBackgroundColor(ChromaRPG, 255);
	TextDrawBoxColor(ChromaRPG, 50);
	TextDrawUseBox(ChromaRPG, 0);
	TextDrawSetProportional(ChromaRPG, 1);
	TextDrawSetSelectable(ChromaRPG, 0);

	RegisterButton = TextDrawCreate(320.000000, 293.000000, "_");
	TextDrawFont(RegisterButton, 1);
	TextDrawLetterSize(RegisterButton, 0.583333, 1.199998);
	TextDrawTextSize(RegisterButton, 297.000000, 101.000000);
	TextDrawSetOutline(RegisterButton, 1);
	TextDrawSetShadow(RegisterButton, 0);
	TextDrawAlignment(RegisterButton, 2);
	TextDrawColor(RegisterButton, -1);
	TextDrawBackgroundColor(RegisterButton, 255);
	TextDrawBoxColor(RegisterButton, 1097458168);
	TextDrawUseBox(RegisterButton, 1);
	TextDrawSetProportional(RegisterButton, 1);
	TextDrawSetSelectable(RegisterButton, 1);

	RegisterText = TextDrawCreate(320.000000, 290.000000, "Registrar");
	TextDrawFont(RegisterText, 1);
	TextDrawLetterSize(RegisterText, 0.379166, 1.600000);
	TextDrawTextSize(RegisterText, 400.000000, 17.000000);
	TextDrawSetOutline(RegisterText, 1);
	TextDrawSetShadow(RegisterText, 0);
	TextDrawAlignment(RegisterText, 2);
	TextDrawColor(RegisterText, -1);
	TextDrawBackgroundColor(RegisterText, 255);
	TextDrawBoxColor(RegisterText, 50);
	TextDrawUseBox(RegisterText, 0);
	TextDrawSetProportional(RegisterText, 1);
	TextDrawSetSelectable(RegisterText, 1);

	return 1;
}

public OnPlayerConnect(playerid)
{
	return 1;
}

public OnPlayerDisconnect(playerid)
{
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, Background);
		TextDrawShowForPlayer(playerid, NameRing);
		TextDrawShowForPlayer(playerid, PassordRing);
		TextDrawShowForPlayer(playerid, NameField);
		TextDrawShowForPlayer(playerid, PassordField);
		TextDrawShowForPlayer(playerid, PasswordText);
		TextDrawShowForPlayer(playerid, NameText);
		TextDrawShowForPlayer(playerid, QuitButton);
		TextDrawShowForPlayer(playerid, ConfirmButton);
		TextDrawShowForPlayer(playerid, QuitText);
		TextDrawShowForPlayer(playerid, ConfirmText);
		TextDrawShowForPlayer(playerid, AnonymousGaming);
		TextDrawShowForPlayer(playerid, ChromaRPG);
		TextDrawShowForPlayer(playerid, RegisterButton);
		TextDrawShowForPlayer(playerid, RegisterText);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
