/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

#include <a_samp>

new PlayerText:BG[MAX_PLAYERS];
new PlayerText:NameBG[MAX_PLAYERS];
new PlayerText:StatsBG[MAX_PLAYERS];
new PlayerText:NameText1[MAX_PLAYERS];
new PlayerText:NameText2[MAX_PLAYERS];
new PlayerText:version[MAX_PLAYERS];
new PlayerText:textdraw_6[MAX_PLAYERS];
new PlayerText:textdraw_7[MAX_PLAYERS];
new PlayerText:textdraw_8[MAX_PLAYERS];
new PlayerText:RegisterButton[MAX_PLAYERS];
new PlayerText:textdraw_10[MAX_PLAYERS];
new PlayerText:QuitButton[MAX_PLAYERS];
new PlayerText:textdraw_12[MAX_PLAYERS];
new PlayerText:textdraw_13[MAX_PLAYERS];
new PlayerText:textdraw_14[MAX_PLAYERS];
new PlayerText:textdraw_15[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	BG[playerid] = CreatePlayerTextDraw(playerid, 37.000000, -5.000000, "_");
	PlayerTextDrawFont(playerid, BG[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BG[playerid], 0.600000, 50.800003);
	PlayerTextDrawTextSize(playerid, BG[playerid], 302.500000, 323.500000);
	PlayerTextDrawSetOutline(playerid, BG[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BG[playerid], 0);
	PlayerTextDrawAlignment(playerid, BG[playerid], 2);
	PlayerTextDrawColor(playerid, BG[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BG[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BG[playerid], 165);
	PlayerTextDrawUseBox(playerid, BG[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BG[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BG[playerid], 0);

	NameBG[playerid] = CreatePlayerTextDraw(playerid, 37.000000, -5.000000, "_");
	PlayerTextDrawFont(playerid, NameBG[playerid], 1);
	PlayerTextDrawLetterSize(playerid, NameBG[playerid], 0.600000, 7.100007);
	PlayerTextDrawTextSize(playerid, NameBG[playerid], 302.500000, 323.500000);
	PlayerTextDrawSetOutline(playerid, NameBG[playerid], 1);
	PlayerTextDrawSetShadow(playerid, NameBG[playerid], 0);
	PlayerTextDrawAlignment(playerid, NameBG[playerid], 2);
	PlayerTextDrawColor(playerid, NameBG[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, NameBG[playerid], 255);
	PlayerTextDrawBoxColor(playerid, NameBG[playerid], 165);
	PlayerTextDrawUseBox(playerid, NameBG[playerid], 1);
	PlayerTextDrawSetProportional(playerid, NameBG[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, NameBG[playerid], 0);

	StatsBG[playerid] = CreatePlayerTextDraw(playerid, 37.000000, 379.000000, "_");
	PlayerTextDrawFont(playerid, StatsBG[playerid], 1);
	PlayerTextDrawLetterSize(playerid, StatsBG[playerid], 0.600000, 7.100007);
	PlayerTextDrawTextSize(playerid, StatsBG[playerid], 302.500000, 323.500000);
	PlayerTextDrawSetOutline(playerid, StatsBG[playerid], 1);
	PlayerTextDrawSetShadow(playerid, StatsBG[playerid], 0);
	PlayerTextDrawAlignment(playerid, StatsBG[playerid], 2);
	PlayerTextDrawColor(playerid, StatsBG[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, StatsBG[playerid], 255);
	PlayerTextDrawBoxColor(playerid, StatsBG[playerid], 165);
	PlayerTextDrawUseBox(playerid, StatsBG[playerid], 1);
	PlayerTextDrawSetProportional(playerid, StatsBG[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, StatsBG[playerid], 0);

	NameText1[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 12.000000, "Anonymous Gaming");
	PlayerTextDrawFont(playerid, NameText1[playerid], 3);
	PlayerTextDrawLetterSize(playerid, NameText1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, NameText1[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, NameText1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, NameText1[playerid], 0);
	PlayerTextDrawAlignment(playerid, NameText1[playerid], 2);
	PlayerTextDrawColor(playerid, NameText1[playerid], 9145343);
	PlayerTextDrawBackgroundColor(playerid, NameText1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, NameText1[playerid], 50);
	PlayerTextDrawUseBox(playerid, NameText1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, NameText1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, NameText1[playerid], 0);

	NameText2[playerid] = CreatePlayerTextDraw(playerid, 82.000000, 31.000000, "Chroma RPG");
	PlayerTextDrawFont(playerid, NameText2[playerid], 3);
	PlayerTextDrawLetterSize(playerid, NameText2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, NameText2[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, NameText2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, NameText2[playerid], 0);
	PlayerTextDrawAlignment(playerid, NameText2[playerid], 2);
	PlayerTextDrawColor(playerid, NameText2[playerid], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, NameText2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, NameText2[playerid], 50);
	PlayerTextDrawUseBox(playerid, NameText2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, NameText2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, NameText2[playerid], 0);

	version[playerid] = CreatePlayerTextDraw(playerid, 162.000000, 36.000000, "v0.0.1");
	PlayerTextDrawFont(playerid, version[playerid], 3);
	PlayerTextDrawLetterSize(playerid, version[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, version[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, version[playerid], 1);
	PlayerTextDrawSetShadow(playerid, version[playerid], 0);
	PlayerTextDrawAlignment(playerid, version[playerid], 2);
	PlayerTextDrawColor(playerid, version[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, version[playerid], 255);
	PlayerTextDrawBoxColor(playerid, version[playerid], 50);
	PlayerTextDrawUseBox(playerid, version[playerid], 0);
	PlayerTextDrawSetProportional(playerid, version[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, version[playerid], 0);

	textdraw_6[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 154.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_6[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_6[playerid], 0.600000, 2.350002);
	PlayerTextDrawTextSize(playerid, textdraw_6[playerid], 338.500000, 159.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_6[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_6[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_6[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_6[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_6[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_6[playerid], 230);
	PlayerTextDrawUseBox(playerid, textdraw_6[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_6[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_6[playerid], 0);

	textdraw_7[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 157.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_7[playerid], 0.600000, 1.700001);
	PlayerTextDrawTextSize(playerid, textdraw_7[playerid], 347.500000, 155.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_7[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_7[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_7[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_7[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_7[playerid], 6553789);
	PlayerTextDrawUseBox(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_7[playerid], 0);

	textdraw_8[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 199.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_8[playerid], 0.600000, 2.300003);
	PlayerTextDrawTextSize(playerid, textdraw_8[playerid], 338.500000, 159.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_8[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_8[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_8[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_8[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_8[playerid], 168430335);
	PlayerTextDrawUseBox(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_8[playerid], 0);

	RegisterButton[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 202.000000, "_");
	PlayerTextDrawFont(playerid, RegisterButton[playerid], 1);
	PlayerTextDrawLetterSize(playerid, RegisterButton[playerid], 0.600000, 1.700003);
	PlayerTextDrawTextSize(playerid, RegisterButton[playerid], 339.500000, 155.500000);
	PlayerTextDrawSetOutline(playerid, RegisterButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, RegisterButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, RegisterButton[playerid], 2);
	PlayerTextDrawColor(playerid, RegisterButton[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, RegisterButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, RegisterButton[playerid], 1097458175);
	PlayerTextDrawUseBox(playerid, RegisterButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, RegisterButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, RegisterButton[playerid], 0);

	textdraw_10[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 330.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_10[playerid], 0.600000, 2.300003);
	PlayerTextDrawTextSize(playerid, textdraw_10[playerid], 338.500000, 159.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_10[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_10[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_10[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_10[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_10[playerid], 168430335);
	PlayerTextDrawUseBox(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_10[playerid], 0);

	QuitButton[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 333.000000, "_");
	PlayerTextDrawFont(playerid, QuitButton[playerid], 1);
	PlayerTextDrawLetterSize(playerid, QuitButton[playerid], 0.600000, 1.700003);
	PlayerTextDrawTextSize(playerid, QuitButton[playerid], 338.500000, 155.500000);
	PlayerTextDrawSetOutline(playerid, QuitButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, QuitButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, QuitButton[playerid], 2);
	PlayerTextDrawColor(playerid, QuitButton[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, QuitButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, QuitButton[playerid], 1509949695);
	PlayerTextDrawUseBox(playerid, QuitButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, QuitButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, QuitButton[playerid], 0);

	textdraw_12[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 434.000000, "Chroma RPG - Todos os direitos reservados");
	PlayerTextDrawFont(playerid, textdraw_12[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_12[playerid], 0.283333, 1.399999);
	PlayerTextDrawTextSize(playerid, textdraw_12[playerid], 610.000000, 337.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_12[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_12[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_12[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_12[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_12[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_12[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_12[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_12[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_12[playerid], 0);

	textdraw_13[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 158.000000, "Login");
	PlayerTextDrawFont(playerid, textdraw_13[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_13[playerid], 0.287499, 1.500002);
	PlayerTextDrawTextSize(playerid, textdraw_13[playerid], 18.000000, 155.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_13[playerid], 0);
	PlayerTextDrawSetShadow(playerid, textdraw_13[playerid], 1);
	PlayerTextDrawAlignment(playerid, textdraw_13[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_13[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_13[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_13[playerid], 255);
	PlayerTextDrawUseBox(playerid, textdraw_13[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_13[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_13[playerid], 1);

	textdraw_14[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 202.000000, "Registrar");
	PlayerTextDrawFont(playerid, textdraw_14[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_14[playerid], 0.287499, 1.700003);
	PlayerTextDrawTextSize(playerid, textdraw_14[playerid], 18.500000, 155.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_14[playerid], 0);
	PlayerTextDrawSetShadow(playerid, textdraw_14[playerid], 1);
	PlayerTextDrawAlignment(playerid, textdraw_14[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_14[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_14[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_14[playerid], 255);
	PlayerTextDrawUseBox(playerid, textdraw_14[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_14[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_14[playerid], 1);

	textdraw_15[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 333.000000, "Sair");
	PlayerTextDrawFont(playerid, textdraw_15[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_15[playerid], 0.287499, 1.700003);
	PlayerTextDrawTextSize(playerid, textdraw_15[playerid], 20.000000, 155.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_15[playerid], 0);
	PlayerTextDrawSetShadow(playerid, textdraw_15[playerid], 1);
	PlayerTextDrawAlignment(playerid, textdraw_15[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_15[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_15[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_15[playerid], 255);
	PlayerTextDrawUseBox(playerid, textdraw_15[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_15[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_15[playerid], 1);

	return 1;
}

public OnPlayerDisconnect(playerid)
{
	PlayerTextDrawDestroy(playerid, BG[playerid]);
	PlayerTextDrawDestroy(playerid, NameBG[playerid]);
	PlayerTextDrawDestroy(playerid, StatsBG[playerid]);
	PlayerTextDrawDestroy(playerid, NameText1[playerid]);
	PlayerTextDrawDestroy(playerid, NameText2[playerid]);
	PlayerTextDrawDestroy(playerid, version[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_6[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_7[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_8[playerid]);
	PlayerTextDrawDestroy(playerid, RegisterButton[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_10[playerid]);
	PlayerTextDrawDestroy(playerid, QuitButton[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_12[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_13[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_14[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_15[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, BG[playerid]);
		PlayerTextDrawShow(playerid, NameBG[playerid]);
		PlayerTextDrawShow(playerid, StatsBG[playerid]);
		PlayerTextDrawShow(playerid, NameText1[playerid]);
		PlayerTextDrawShow(playerid, NameText2[playerid]);
		PlayerTextDrawShow(playerid, version[playerid]);
		PlayerTextDrawShow(playerid, textdraw_6[playerid]);
		PlayerTextDrawShow(playerid, textdraw_7[playerid]);
		PlayerTextDrawShow(playerid, textdraw_8[playerid]);
		PlayerTextDrawShow(playerid, RegisterButton[playerid]);
		PlayerTextDrawShow(playerid, textdraw_10[playerid]);
		PlayerTextDrawShow(playerid, QuitButton[playerid]);
		PlayerTextDrawShow(playerid, textdraw_12[playerid]);
		PlayerTextDrawShow(playerid, textdraw_13[playerid]);
		PlayerTextDrawShow(playerid, textdraw_14[playerid]);
		PlayerTextDrawShow(playerid, textdraw_15[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
