/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

#include <a_samp>

new PlayerText:BG1[MAX_PLAYERS];
new PlayerText:NameBG1[MAX_PLAYERS];
new PlayerText:StatsBG1[MAX_PLAYERS];
new PlayerText:1NameText1[MAX_PLAYERS];
new PlayerText:1NameText2[MAX_PLAYERS];
new PlayerText:Version1[MAX_PLAYERS];
new PlayerText:NameTBox1[MAX_PLAYERS];
new PlayerText:textdraw_7[MAX_PLAYERS];
new PlayerText:textdraw_8[MAX_PLAYERS];
new PlayerText:textdraw_9[MAX_PLAYERS];
new PlayerText:textdraw_10[MAX_PLAYERS];
new PlayerText:textdraw_11[MAX_PLAYERS];
new PlayerText:Copright1[MAX_PLAYERS];
new PlayerText:textdraw_13[MAX_PLAYERS];
new PlayerText:textdraw_14[MAX_PLAYERS];
new PlayerText:textdraw_15[MAX_PLAYERS];
new PlayerText:textdraw_16[MAX_PLAYERS];
new PlayerText:textdraw_17[MAX_PLAYERS];
new PlayerText:textdraw_18[MAX_PLAYERS];
new PlayerText:textdraw_19[MAX_PLAYERS];
new PlayerText:textdraw_20[MAX_PLAYERS];
new PlayerText:textdraw_21[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	BG1[playerid] = CreatePlayerTextDraw(playerid, 37.000000, -5.000000, "_");
	PlayerTextDrawFont(playerid, BG1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, BG1[playerid], 0.600000, 50.800003);
	PlayerTextDrawTextSize(playerid, BG1[playerid], 302.500000, 323.500000);
	PlayerTextDrawSetOutline(playerid, BG1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BG1[playerid], 0);
	PlayerTextDrawAlignment(playerid, BG1[playerid], 2);
	PlayerTextDrawColor(playerid, BG1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BG1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BG1[playerid], 165);
	PlayerTextDrawUseBox(playerid, BG1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BG1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BG1[playerid], 0);

	NameBG1[playerid] = CreatePlayerTextDraw(playerid, 37.000000, -5.000000, "_");
	PlayerTextDrawFont(playerid, NameBG1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, NameBG1[playerid], 0.600000, 7.100007);
	PlayerTextDrawTextSize(playerid, NameBG1[playerid], 302.500000, 323.500000);
	PlayerTextDrawSetOutline(playerid, NameBG1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, NameBG1[playerid], 0);
	PlayerTextDrawAlignment(playerid, NameBG1[playerid], 2);
	PlayerTextDrawColor(playerid, NameBG1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, NameBG1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, NameBG1[playerid], 165);
	PlayerTextDrawUseBox(playerid, NameBG1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, NameBG1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, NameBG1[playerid], 0);

	StatsBG1[playerid] = CreatePlayerTextDraw(playerid, 37.000000, 379.000000, "_");
	PlayerTextDrawFont(playerid, StatsBG1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, StatsBG1[playerid], 0.600000, 7.100007);
	PlayerTextDrawTextSize(playerid, StatsBG1[playerid], 302.500000, 323.500000);
	PlayerTextDrawSetOutline(playerid, StatsBG1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, StatsBG1[playerid], 0);
	PlayerTextDrawAlignment(playerid, StatsBG1[playerid], 2);
	PlayerTextDrawColor(playerid, StatsBG1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, StatsBG1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, StatsBG1[playerid], 165);
	PlayerTextDrawUseBox(playerid, StatsBG1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, StatsBG1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, StatsBG1[playerid], 0);

	1NameText1[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 12.000000, "Anonymous Gaming");
	PlayerTextDrawFont(playerid, 1NameText1[playerid], 3);
	PlayerTextDrawLetterSize(playerid, 1NameText1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, 1NameText1[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, 1NameText1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, 1NameText1[playerid], 0);
	PlayerTextDrawAlignment(playerid, 1NameText1[playerid], 2);
	PlayerTextDrawColor(playerid, 1NameText1[playerid], 9145343);
	PlayerTextDrawBackgroundColor(playerid, 1NameText1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, 1NameText1[playerid], 50);
	PlayerTextDrawUseBox(playerid, 1NameText1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, 1NameText1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, 1NameText1[playerid], 0);

	1NameText2[playerid] = CreatePlayerTextDraw(playerid, 82.000000, 31.000000, "Chroma RPG");
	PlayerTextDrawFont(playerid, 1NameText2[playerid], 3);
	PlayerTextDrawLetterSize(playerid, 1NameText2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, 1NameText2[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, 1NameText2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, 1NameText2[playerid], 0);
	PlayerTextDrawAlignment(playerid, 1NameText2[playerid], 2);
	PlayerTextDrawColor(playerid, 1NameText2[playerid], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, 1NameText2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, 1NameText2[playerid], 50);
	PlayerTextDrawUseBox(playerid, 1NameText2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, 1NameText2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, 1NameText2[playerid], 0);

	Version1[playerid] = CreatePlayerTextDraw(playerid, 162.000000, 36.000000, "v0.0.1");
	PlayerTextDrawFont(playerid, Version1[playerid], 3);
	PlayerTextDrawLetterSize(playerid, Version1[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, Version1[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, Version1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Version1[playerid], 0);
	PlayerTextDrawAlignment(playerid, Version1[playerid], 2);
	PlayerTextDrawColor(playerid, Version1[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, Version1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Version1[playerid], 50);
	PlayerTextDrawUseBox(playerid, Version1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Version1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Version1[playerid], 0);

	NameTBox1[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 149.000000, "_");
	PlayerTextDrawFont(playerid, NameTBox1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, NameTBox1[playerid], 0.600000, 1.900006);
	PlayerTextDrawTextSize(playerid, NameTBox1[playerid], 302.500000, 169.000000);
	PlayerTextDrawSetOutline(playerid, NameTBox1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, NameTBox1[playerid], 0);
	PlayerTextDrawAlignment(playerid, NameTBox1[playerid], 2);
	PlayerTextDrawColor(playerid, NameTBox1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, NameTBox1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, NameTBox1[playerid], 255);
	PlayerTextDrawUseBox(playerid, NameTBox1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, NameTBox1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, NameTBox1[playerid], 0);

	textdraw_7[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 153.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_7[playerid], 0.600000, 1.150007);
	PlayerTextDrawTextSize(playerid, textdraw_7[playerid], 302.500000, 164.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_7[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_7[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_7[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_7[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_7[playerid], -68);
	PlayerTextDrawUseBox(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_7[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_7[playerid], 0);

	textdraw_8[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 200.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_8[playerid], 0.600000, 1.900006);
	PlayerTextDrawTextSize(playerid, textdraw_8[playerid], 302.500000, 169.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_8[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_8[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_8[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_8[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_8[playerid], 255);
	PlayerTextDrawUseBox(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_8[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_8[playerid], 0);

	textdraw_9[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 203.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_9[playerid], 0.600000, 1.250005);
	PlayerTextDrawTextSize(playerid, textdraw_9[playerid], 302.500000, 164.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_9[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_9[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_9[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_9[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_9[playerid], -68);
	PlayerTextDrawUseBox(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_9[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_9[playerid], 0);

	textdraw_10[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 84.000000, "Login");
	PlayerTextDrawFont(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_10[playerid], 0.604165, 2.049998);
	PlayerTextDrawTextSize(playerid, textdraw_10[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_10[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_10[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_10[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_10[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_10[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_10[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_10[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_10[playerid], 0);

	textdraw_11[playerid] = CreatePlayerTextDraw(playerid, 31.000000, 130.000000, "Nome");
	PlayerTextDrawFont(playerid, textdraw_11[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_11[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, textdraw_11[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_11[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_11[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_11[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_11[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_11[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_11[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_11[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_11[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_11[playerid], 0);

	Copright1[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 434.000000, "Chroma RPG - Todos os direitos reservados");
	PlayerTextDrawFont(playerid, Copright1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, Copright1[playerid], 0.283333, 1.399999);
	PlayerTextDrawTextSize(playerid, Copright1[playerid], 610.000000, 337.000000);
	PlayerTextDrawSetOutline(playerid, Copright1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Copright1[playerid], 0);
	PlayerTextDrawAlignment(playerid, Copright1[playerid], 2);
	PlayerTextDrawColor(playerid, Copright1[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, Copright1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Copright1[playerid], 50);
	PlayerTextDrawUseBox(playerid, Copright1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, Copright1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Copright1[playerid], 0);

	textdraw_13[playerid] = CreatePlayerTextDraw(playerid, 14.000000, 181.000000, "Senha");
	PlayerTextDrawFont(playerid, textdraw_13[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_13[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, textdraw_13[playerid], 400.000000, 198.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_13[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_13[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_13[playerid], 1);
	PlayerTextDrawColor(playerid, textdraw_13[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_13[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_13[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_13[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_13[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_13[playerid], 0);

	textdraw_14[playerid] = CreatePlayerTextDraw(playerid, 17.000000, 150.000000, "Nomedoplayer");
	PlayerTextDrawFont(playerid, textdraw_14[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_14[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, textdraw_14[playerid], 182.000000, 18.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_14[playerid], 0);
	PlayerTextDrawSetShadow(playerid, textdraw_14[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_14[playerid], 1);
	PlayerTextDrawColor(playerid, textdraw_14[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, textdraw_14[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_14[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_14[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_14[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_14[playerid], 0);

	textdraw_15[playerid] = CreatePlayerTextDraw(playerid, 17.000000, 193.000000, ".............");
	PlayerTextDrawFont(playerid, textdraw_15[playerid], 0);
	PlayerTextDrawLetterSize(playerid, textdraw_15[playerid], 0.670831, 2.349997);
	PlayerTextDrawTextSize(playerid, textdraw_15[playerid], 183.000000, 20.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_15[playerid], 0);
	PlayerTextDrawSetShadow(playerid, textdraw_15[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_15[playerid], 1);
	PlayerTextDrawColor(playerid, textdraw_15[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, textdraw_15[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_15[playerid], 50);
	PlayerTextDrawUseBox(playerid, textdraw_15[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_15[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_15[playerid], 1);

	textdraw_16[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 342.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_16[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_16[playerid], 0.600000, 1.900006);
	PlayerTextDrawTextSize(playerid, textdraw_16[playerid], 302.500000, 169.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_16[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_16[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_16[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_16[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_16[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_16[playerid], 255);
	PlayerTextDrawUseBox(playerid, textdraw_16[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_16[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_16[playerid], 0);

	textdraw_17[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 345.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_17[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_17[playerid], 0.600000, 1.150006);
	PlayerTextDrawTextSize(playerid, textdraw_17[playerid], 302.500000, 164.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_17[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_17[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_17[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_17[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_17[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_17[playerid], -1962934084);
	PlayerTextDrawUseBox(playerid, textdraw_17[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_17[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_17[playerid], 0);

	textdraw_18[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 312.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_18[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_18[playerid], 0.600000, 1.900006);
	PlayerTextDrawTextSize(playerid, textdraw_18[playerid], 302.500000, 169.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_18[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_18[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_18[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_18[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_18[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_18[playerid], 255);
	PlayerTextDrawUseBox(playerid, textdraw_18[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_18[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_18[playerid], 0);

	textdraw_19[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 315.000000, "_");
	PlayerTextDrawFont(playerid, textdraw_19[playerid], 1);
	PlayerTextDrawLetterSize(playerid, textdraw_19[playerid], 0.600000, 1.150006);
	PlayerTextDrawTextSize(playerid, textdraw_19[playerid], 302.500000, 164.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_19[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_19[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_19[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_19[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, textdraw_19[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_19[playerid], 9109692);
	PlayerTextDrawUseBox(playerid, textdraw_19[playerid], 1);
	PlayerTextDrawSetProportional(playerid, textdraw_19[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_19[playerid], 0);

	textdraw_20[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 312.000000, "Entrar");
	PlayerTextDrawFont(playerid, textdraw_20[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_20[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, textdraw_20[playerid], 19.000000, 164.500000);
	PlayerTextDrawSetOutline(playerid, textdraw_20[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_20[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_20[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_20[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_20[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_20[playerid], 197);
	PlayerTextDrawUseBox(playerid, textdraw_20[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_20[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_20[playerid], 1);

	textdraw_21[playerid] = CreatePlayerTextDraw(playerid, 100.000000, 343.000000, "Voltar");
	PlayerTextDrawFont(playerid, textdraw_21[playerid], 2);
	PlayerTextDrawLetterSize(playerid, textdraw_21[playerid], 0.291666, 1.500000);
	PlayerTextDrawTextSize(playerid, textdraw_21[playerid], 19.000000, 164.000000);
	PlayerTextDrawSetOutline(playerid, textdraw_21[playerid], 1);
	PlayerTextDrawSetShadow(playerid, textdraw_21[playerid], 0);
	PlayerTextDrawAlignment(playerid, textdraw_21[playerid], 2);
	PlayerTextDrawColor(playerid, textdraw_21[playerid], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, textdraw_21[playerid], 255);
	PlayerTextDrawBoxColor(playerid, textdraw_21[playerid], 206);
	PlayerTextDrawUseBox(playerid, textdraw_21[playerid], 0);
	PlayerTextDrawSetProportional(playerid, textdraw_21[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, textdraw_21[playerid], 1);

	return 1;
}

public OnPlayerDisconnect(playerid)
{
	PlayerTextDrawDestroy(playerid, BG1[playerid]);
	PlayerTextDrawDestroy(playerid, NameBG1[playerid]);
	PlayerTextDrawDestroy(playerid, StatsBG1[playerid]);
	PlayerTextDrawDestroy(playerid, 1NameText1[playerid]);
	PlayerTextDrawDestroy(playerid, 1NameText2[playerid]);
	PlayerTextDrawDestroy(playerid, Version1[playerid]);
	PlayerTextDrawDestroy(playerid, NameTBox1[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_7[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_8[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_9[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_10[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_11[playerid]);
	PlayerTextDrawDestroy(playerid, Copright1[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_13[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_14[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_15[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_16[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_17[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_18[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_19[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_20[playerid]);
	PlayerTextDrawDestroy(playerid, textdraw_21[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, BG1[playerid]);
		PlayerTextDrawShow(playerid, NameBG1[playerid]);
		PlayerTextDrawShow(playerid, StatsBG1[playerid]);
		PlayerTextDrawShow(playerid, 1NameText1[playerid]);
		PlayerTextDrawShow(playerid, 1NameText2[playerid]);
		PlayerTextDrawShow(playerid, Version1[playerid]);
		PlayerTextDrawShow(playerid, NameTBox1[playerid]);
		PlayerTextDrawShow(playerid, textdraw_7[playerid]);
		PlayerTextDrawShow(playerid, textdraw_8[playerid]);
		PlayerTextDrawShow(playerid, textdraw_9[playerid]);
		PlayerTextDrawShow(playerid, textdraw_10[playerid]);
		PlayerTextDrawShow(playerid, textdraw_11[playerid]);
		PlayerTextDrawShow(playerid, Copright1[playerid]);
		PlayerTextDrawShow(playerid, textdraw_13[playerid]);
		PlayerTextDrawShow(playerid, textdraw_14[playerid]);
		PlayerTextDrawShow(playerid, textdraw_15[playerid]);
		PlayerTextDrawShow(playerid, textdraw_16[playerid]);
		PlayerTextDrawShow(playerid, textdraw_17[playerid]);
		PlayerTextDrawShow(playerid, textdraw_18[playerid]);
		PlayerTextDrawShow(playerid, textdraw_19[playerid]);
		PlayerTextDrawShow(playerid, textdraw_20[playerid]);
		PlayerTextDrawShow(playerid, textdraw_21[playerid]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
