/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <DOF2>
#include <zcmd>

#define CONTAS "contas/%s.ini"

#define DIALOG_ID 150

new fome[MAX_PLAYERS], sede[MAX_PLAYERS],sono[MAX_PLAYERS],Experiencia[MAX_PLAYERS]
new PlayerText:PlayerTD[MAX_PLAYERS][11];
new PlayerText:ClockTD[MAX_PLAYERS][2];
new timerUp[MAX_PLAYERS];
new timerSTATS[MAX_PLAYERS];
new timerClock[MAX_PLAYERS];
new timerFome[MAX_PLAYERS];
new timerSede[MAX_PLAYERS];
new timerSono[MAX_PLAYERS];



forward Stats(playerid);
public Stats(playerid){
	new s1[128];
	new file[128];
	new stars[MAX_PLAYERS];
	format(file, sizeof(file), "contas/%s.ini", PlayerName(playerid));
	PlayerTextDrawHide(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawHide(playerid, PlayerTD[playerid][10]);
	
	format(s1, sizeof(s1), "%d/6", Experiencia[playerid]);
	
	PlayerTextDrawSetString(playerid, PlayerTD[playerid][1], s1);
	format(s1, sizeof(s1), "%d", fome[playerid]);
	PlayerTextDrawSetString(playerid, PlayerTD[playerid][7], s1);
	format(s1, sizeof(s1), "%d", sede[playerid]);
	PlayerTextDrawSetString(playerid, PlayerTD[playerid][8], s1);

	PlayerTextDrawSetString(playerid, PlayerTD[playerid][9], "100");
	format(s1, sizeof(s1), "%d", sono[playerid]);
	PlayerTextDrawSetString(playerid, PlayerTD[playerid][10], s1);


	PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);

	return 1;
}

forward LvlUP(playerid);
public LvlUP(playerid){
	new file[128];
	format(file, sizeof(file), "contas/%s.ini", PlayerName(playerid));
	if(Experiencia[playerid] < 6){
		new s1[128];
		Experiencia[playerid]++;
		format(s1, sizeof(s1), "{00FF00}[UP] {FFFFFF}Voce recebeu 1 de Exp. (%d/6)", Experiencia[playerid]);
		DOF2_SetInt(file, "Exp", Experiencia[playerid])
		SendClientMessage(playerid, -1, s1);
	}else{
		new s1[128];
		Experiencia[playerid] = 0;
		SetPlayerScore(playerid, GetPlayerScore(playerid) +1);
		DOF2_SetInt(file, "Exp", Experiencia[playerid]);
		DOF2_SetInt(file, "Lrvel", Experiencia[playerid]);
		
		format(s1, sizeof(s1), "{00FF00}[UP] {FFFFFF}Voce juntou 6 de Exp e alcançou o nivel %d.", GetPlayerScore(playerid));
		SendClientMessage(playerid, -1, s1);
	}
	
	return 1;
}

forward updateFome(playerid);
public updateFome(playerid){
	if(fome[playerid] > 0 && fome[playerid] <= 100){
		fome[playerid]--;
	}else{

	}
}
forward updateSede(playerid);
public updateSede(playerid){
	if(sede[playerid] > 0 && sede[playerid] <= 100){
		sede[playerid]--;
	}else{

	}
}
forward updateSono(playerid);
public updateSono(playerid){
	if(sono[playerid] > 0 && sono[playerid] <= 100){
		sono[playerid]--;
	}else{

	}
}


stock createtd(playerid){
		
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 95.000000, 237.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.554166, 2.449999);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 97.5000000, 237.000000, "00:00");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.554166, 2.449999);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 22.000000, 237.000000, "Lvl");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.487499, 2.399999);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 9109554);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 24.000000, 265.000000, "HUD:radar_pizza");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 19.000000, 22.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 51.000000, 265.000000, "HUD:radar_datedrink");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 19.000000, 22.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 77.000000, 265.000000, "HUD:radar_hostpital");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 19.000000, 22.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 104.000000, 264.000000, "HUD:radar_propertyg");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 19.000000, 22.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 24.000000, 291.000000, "100");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.304165, 2.149998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 9109554);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 50.000000, 291.000000, "100");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.304165, 2.149998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 9109554);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 77.000000, 291.000000, "100");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.304165, 2.149998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 9109554);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 104.000000, 291.000000, "100");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 3);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.304165, 2.149998);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 9109554);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

}
public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}
stock PlayerName(playerid){
	new string[MAX_PLAYER_NAME];
	GetPlayerName(playerid, string, sizeof(string));
	return string;

}

public OnPlayerConnect(playerid)
{
	

	// PlayerTextDrawHide(playerid, PlayerTD[playerid][1]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][2]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][3]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][4]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][5]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][6]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][7]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][8]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][9]);
	// PlayerTextDrawHide(playerid, PlayerTD[playerid][10]);

	return 1;
}

public OnPlayerDisconnect(playerid)
{
	new file[128];
	format(file, sizeof(file), CONTAS, PlayerName(playerid));
	KillTimer(timerSTATS[playerid]);
	KillTimer(timerUp[playerid]);
	KillTimer(timerSono[playerid]);
	KillTimer(timerSede[playerid]);
	KillTimer(timerFome[playerid]);


	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);

	DOF2_SetInt(file, "Fome", fome[playerid]);
	DOF2_SetInt(file, "Sede", sede[playerid]);
	DOF2_SetInt(file, "Sono", sono[playerid]);

	return 1;
}
forward start(playerid);
public start(playerid){
	timerSTATS[playerid] = SetTimer("Stats", 500, true);
	timerUp[playerid] = SetTimer("LvlUP", 600000, true);
	

	timerSono[playerid] = SetTimer("updateSono", 30000, true);
	timerSede[playerid] = SetTimer("updateSede", 15000, true);
	timerFome[playerid] = SetTimer("updateFome", 20000, true);
	return 1;
}
public OnPlayerSpawn(playerid)
{
	SetTimer("start", 1000, false);
	new file[128];
	format(file, sizeof(file), CONTAS, PlayerName(playerid));
	fome[playerid] = DOF2_GetInt(file, "Fome");
	sede[playerid] = DOF2_GetInt(file, "Sede");
	sono[playerid] = DOF2_GetInt(file, "Sono");
	
	Experiencia[playerid] = DOF2_GetInt(file, "Exp");
	//GivePlayerMoney(playerid, DOF2_GetInt(file, "Money"));
	SetPlayerScore(playerid, DOF2_GetInt(file, "Level"));
	createtd(playerid);

	return 1;
	
}
public OnPlayerUpdate(playerid)
{
	return 1;
}




//==================COMANDOS==================

CMD:identidade(playerid, params[]){
	new file[128];
	new msg[10000];
	new hab[128],habar[128],habm[128],vip[128],porte[128],lincencaM[128],licencaAR[128],licencaWater[128];
	format(file, sizeof(file), CONTAS, PlayerName(playerid));
	if(DOF2_GetInt(file, "HabTerrestre") == 1){
		format(hab, sizeof(hab), "Sim");
	}else if(DOF2_GetInt(file, "HabTerrestre") == 0){
		format(hab, sizeof(hab), "Nao");
	}

	if(DOF2_GetInt(file, "HabAerea") == 1){
		format(habar, sizeof(habar), "Sim");
	}else if(DOF2_GetInt(file, "HabAerea") == 0){
		format(habar, sizeof(habar), "Nao");
	}

	if(DOF2_GetInt(file, "HabAquatica") == 1){
		format(habm, sizeof(habm), "Sim");
	}else if(DOF2_GetInt(file, "HabAquatica") == 0){
		format(habm, sizeof(habm), "Nao");
	}

	if(DOF2_GetInt(file, "IsVip") == 1){
		format(vip, sizeof(vip), "Sim");
	}else if(DOF2_GetInt(file, "IsVip") == 0){
		format(vip, sizeof(vip), "Nao");
	}


	if(DOF2_GetInt(file, "Porte de Armas") == 1){
		format(porte, sizeof(porte), "Sim");
	}else if(DOF2_GetInt(file, "Porte de Armas") == 0){
		format(porte, sizeof(porte), "Nao");
	}

	if(DOF2_GetInt(file, "Exercito") == 1){
		format(lincencaM, sizeof(lincencaM), "Sim");
	}else if(DOF2_GetInt(file, "Exercito") == 0){
		format(lincencaM, sizeof(lincencaM), "Nao");
	}

	if(DOF2_GetInt(file, "Marinha") == 1){
		format(licencaWater, sizeof(licencaWater), "Sim");
	}else if(DOF2_GetInt(file, "Marinha") == 0){
		format(licencaWater, sizeof(licencaWater), "Nao");
	}

	if(DOF2_GetInt(file, "Aeronautica") == 1){
		format(licencaAR, sizeof(licencaAR), "Sim");
	}else if(DOF2_GetInt(file, "Aeronautica") == 0){
		format(licencaAR, sizeof(licencaAR), "Nao");
	}
	new str[1000]
	format(msg, sizeof(msg), "{00FF00}Nome: {FFFFFF}%s\n", PlayerName(playerid));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Level: {FFFFFF}%d\n",GetPlayerScore(playerid));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Exp: {FFFFFF}%d\n", DOF2_GetInt(file, "Exp"));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Nivel de procurado: {FFFFFF}%d\n", DOF2_GetInt(file, "Nivel de procurado"));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Email: {FFFFFF}%s\n", DOF2_GetString(file, "Email"));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Skin ID: {FFFFFF}%d\n", DOF2_GetInt(file, "Skin"));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Dinheiro: {FFFFFF}$%d\n", GetPlayerMoney(playerid));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Habilitacao Terrestre: {FFFFFF}%s\n", hab);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Habilitacao Aerea: {FFFFFF}%s\n", habar);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Habilitacao Maritima: {FFFFFF}%s\n", habm);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Emprego: {FFFFFF}%s\n", DOF2_GetString(file,"Emprego"));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Salario: {FFFFFF}%d\n", DOF2_GetInt(file, "Salario"));
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Vip: {FFFFFF}%s\n", vip);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Porte de armas: {FFFFFF}%s\n", porte);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Licenca do Exercito: {FFFFFF}%s\n", lincencaM);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Licenca da Aeronautica: {FFFFFF}%s\n", licencaAR);
	strcat(str, msg);
	format(msg, sizeof(msg), "{00FF00}Licenca da Marinha: {FFFFFF}%s", licencaWater);
	strcat(str, msg);
	ShowPlayerDialog(playerid, DIALOG_ID, DIALOG_STYLE_MSGBOX, "Identidade", str, "Ok");

	return 1;
}

//==================COMANDOS==================
