/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <DOF2>
#include <sscanf>
#include <zcmd>


public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}
new Onibus1;
public OnPlayerConnect(playerid)
{
	if(IsPlayerNPC(playerid)) //Verifica se o jogador é um NPC.
  	{
    	new npcname[MAX_PLAYER_NAME];
    	GetPlayerName(playerid, npcname, sizeof(npcname)); //Obtendo o nome do(s) NPC(s).
    	if(!strcmp(npcname, "test", true)) //Checando se o nome do NPC é MeuPrimeiroNPC
    	{
			SpawnPlayer(playerid);
    		PutPlayerInVehicle(playerid, Onibus1, 0); //Colocar o NPC dentro do veículo que criamos para isso.	
		  
    	}
  	}
	return 1;
}

public OnPlayerDisconnect(playerid)
{
	
}
public OnPlayerRequestSpawn(playerid){

	return 1;
}
public OnPlayerSpawn(playerid){
	if(IsPlayerNPC(playerid)) PutPlayerInVehicle(playerid, Onibus1, 0);

	return 1;
}

CMD:connectnpc(playerid, params[]){
	ConnectNPC("test","Teste");
	Onibus1 = CreateVehicle(431, 0.0, 0.0, 5.0, 0.0, 3, 3, 5000);
	SendClientMessage(playerid, -1, "{00FF00}NPC conectado.")
	return 1;
}
CMD:v(playerid, params[]){
	new float:x[MAX_PLAYERS], float:y[MAX_PLAYERS], float:z[MAX_PLAYERS];
	GetPlayerPos(playerid, x[playerid], y[playerid], z[playerid]);
	AddStaticVehicle(411, x[playerid], y[playerid], z[playerid], 0.0, -1, -1);
	SendClientMessage(playerid, -1, "{0000FF}Veiculo spawnado");
	return 1;
}
CMD:tp(playerid, params[]){
	new float:x, float:y, float:z
	if(sscanf(params,"fff",x,y,z)) return SendClientMessage(playerid, -1, "{FF0000}[ERRO]{FFFFFF}Digite /tp [x] [y] [z]");
	SetPlayerPos(playerid, x, y, z);
	SendClientMessage(playerid, -1, "{00FF00}TELEPORTADO");
	return 1;
}

CMD:j(playerid, params[]){
	SendClientMessage(playerid, -1, "{00FF00}[JETPACK]{FFFFFF}Jetpack concedida.");
	SetPlayerSpecialAction (playerid, SPECIAL_ACTION_USEJETPACK);
	return 1;
}
CMD:spawn(playerid, params[]){
		SetPlayerInterior(playerid, 0);
		SetPlayerPos(playerid, 1481.060546, -1767.387573, 18.795755);
		SendClientMessage(playerid, -1, "{00FF00}Teleportado com sucesso para o spawn.");
		return 1;
}
CMD:spawnplayer(playerid, params[]){
	SpawnPlayer(playerid);
	return 1;
}

